//=============================================================================
// audio_equalizer.cpp
//
// Vitis HLS implementation of a real-time FFT-based audio equalizer.
//
// Pipeline:
//   AXI Stream In → Buffer → FFT → Band Gain → IFFT → Buffer → AXI Stream Out
//
// The top-level function uses:
//   - AXI4-Stream  for audio sample I/O
//   - AXI4-Lite    for gain control registers (gain_low, gain_mid, gain_high)
//
// Target: PYNQ-Z2 (Zynq XC7Z020), Vitis HLS 2022.x+
//=============================================================================

#include "audio_equalizer.h"
#include <hls_math.h>

// ─── Internal Types ──────────────────────────────────────────────────────────

// Wider accumulator to avoid overflow during FFT butterfly operations
typedef ap_fixed<32, 10> acc_t;

// Complex number struct for FFT computation
struct complex_t {
    fft_data_t re;
    fft_data_t im;
};

// ─── Twiddle Factor LUT ──────────────────────────────────────────────────────
// Precomputed cosine/sine values for FFT butterfly stages.
// W_N^k = cos(2πk/N) - j*sin(2πk/N), k = 0..N/2-1
static const fft_data_t cos_lut[FFT_SIZE / 2] = {
#include "cos_lut.h"   // generated by scripts/gen_lut.py at synthesis time
};
static const fft_data_t sin_lut[FFT_SIZE / 2] = {
#include "sin_lut.h"
};

// ─── Bit-Reversal Permutation ─────────────────────────────────────────────────
static void bit_reverse(complex_t data[FFT_SIZE]) {
#pragma HLS INLINE
    for (int i = 1, j = 0; i < FFT_SIZE; i++) {
#pragma HLS PIPELINE II=1
        int bit = FFT_SIZE >> 1;
        for (; j & bit; bit >>= 1) j ^= bit;
        j ^= bit;
        if (i < j) {
            complex_t tmp = data[i];
            data[i] = data[j];
            data[j] = tmp;
        }
    }
}

// ─── Cooley-Tukey Radix-2 DIT FFT / IFFT ──────────────────────────────────────
// inverse=false → FFT, inverse=true → IFFT (divides by N at end)
static void fft_core(complex_t data[FFT_SIZE], bool inverse) {
#pragma HLS INLINE off
    bit_reverse(data);

    // Butterfly stages
    for (int s = 1; s <= FFT_SIZE_LOG2; s++) {
#pragma HLS PIPELINE off
        int m = 1 << s;       // DFT sub-problem size
        int half_m = m >> 1;
        int lut_step = FFT_SIZE / m;

        for (int k = 0; k < FFT_SIZE; k += m) {
#pragma HLS PIPELINE off
            for (int j = 0; j < half_m; j++) {
#pragma HLS PIPELINE II=2
                int lut_idx = j * lut_step;
                fft_data_t wr =  cos_lut[lut_idx];
                fft_data_t wi = (inverse) ? sin_lut[lut_idx] : -sin_lut[lut_idx];

                complex_t u = data[k + j];
                complex_t t;
                t.re = (acc_t)wr * data[k + j + half_m].re
                     - (acc_t)wi * data[k + j + half_m].im;
                t.im = (acc_t)wr * data[k + j + half_m].im
                     + (acc_t)wi * data[k + j + half_m].re;

                data[k + j].re         = u.re + t.re;
                data[k + j].im         = u.im + t.im;
                data[k + j + half_m].re = u.re - t.re;
                data[k + j + half_m].im = u.im - t.im;
            }
        }
    }

    // Scale IFFT output by 1/N
    if (inverse) {
        fft_data_t inv_n = (fft_data_t)(1.0f / FFT_SIZE);
        for (int i = 0; i < FFT_SIZE; i++) {
#pragma HLS PIPELINE II=1
            data[i].re = (acc_t)data[i].re * inv_n;
            data[i].im = (acc_t)data[i].im * inv_n;
        }
    }
}

// ─── Frequency-Domain Gain Application ───────────────────────────────────────
// Multiplies each FFT bin by the appropriate band gain.
// Mirror bins (N/2+1 .. N-1) are processed symmetrically to preserve
// real-valued output after IFFT.
static void apply_gains(complex_t freq[FFT_SIZE],
                         gain_t gain_low,
                         gain_t gain_mid,
                         gain_t gain_high)
{
#pragma HLS INLINE
    for (int i = 0; i <= FFT_SIZE / 2; i++) {
#pragma HLS PIPELINE II=1
        gain_t g;
        if      (i <= LOW_HIGH_BIN) g = gain_low;
        else if (i <= MID_HIGH_BIN) g = gain_mid;
        else                         g = gain_high;

        freq[i].re = (acc_t)freq[i].re * g;
        freq[i].im = (acc_t)freq[i].im * g;

        // Mirror bin (skip DC=0 and Nyquist=N/2 which are self-conjugate)
        if (i > 0 && i < FFT_SIZE / 2) {
            int mirror = FFT_SIZE - i;
            freq[mirror].re = (acc_t)freq[mirror].re * g;
            freq[mirror].im = (acc_t)freq[mirror].im * g;
        }
    }
}

// ─── Top-Level Function ───────────────────────────────────────────────────────
// Processes one FFT_SIZE-sample frame per invocation.
//
// HLS Interface directives:
//   s_axis_audio_in  → AXI4-Stream slave  (audio input from codec)
//   m_axis_audio_out → AXI4-Stream master (audio output to codec)
//   gain_*           → AXI4-Lite slave registers (from Python sliders)
void audio_equalizer(
    hls::stream<audio_sample_t> &s_axis_audio_in,
    hls::stream<audio_sample_t> &m_axis_audio_out,
    gain_t gain_low,
    gain_t gain_mid,
    gain_t gain_high)
{
#pragma HLS INTERFACE axis          port=s_axis_audio_in
#pragma HLS INTERFACE axis          port=m_axis_audio_out
#pragma HLS INTERFACE s_axilite     port=gain_low    bundle=CTRL
#pragma HLS INTERFACE s_axilite     port=gain_mid    bundle=CTRL
#pragma HLS INTERFACE s_axilite     port=gain_high   bundle=CTRL
#pragma HLS INTERFACE s_axilite     port=return      bundle=CTRL

    // Working buffer: complex samples for in-place FFT
    complex_t frame[FFT_SIZE];
#pragma HLS ARRAY_PARTITION variable=frame cyclic factor=4 dim=1

    // ── Stage 1: Read audio frame from AXI Stream ─────────────────────────
    read_loop: for (int i = 0; i < FFT_SIZE; i++) {
#pragma HLS PIPELINE II=1
        audio_sample_t s = s_axis_audio_in.read();
        // Sign-extend 24-bit sample from bits [23:0] of 32-bit word
        ap_int<24> raw = s.data.range(23, 0);
        frame[i].re = (sample_t)raw / (sample_t)(1 << 23);  // normalize to [-1, 1)
        frame[i].im = 0;
    }

    // ── Stage 2: Forward FFT ──────────────────────────────────────────────
    fft_core(frame, false);

    // ── Stage 3: Apply per-band gains ─────────────────────────────────────
    apply_gains(frame, gain_low, gain_mid, gain_high);

    // ── Stage 4: Inverse FFT ──────────────────────────────────────────────
    fft_core(frame, true);

    // ── Stage 5: Write processed frame to AXI Stream ─────────────────────
    write_loop: for (int i = 0; i < FFT_SIZE; i++) {
#pragma HLS PIPELINE II=1
        // Scale back to 24-bit integer range and pack into 32-bit word
        ap_int<24> out_sample = (ap_int<24>)((acc_t)frame[i].re * (sample_t)(1 << 23));
        audio_sample_t s;
        s.data.range(23, 0) = out_sample;
        s.data.range(31, 24) = 0;
        s.keep = 0xF;
        s.strb = 0xF;
        s.last  = (i == FFT_SIZE - 1) ? 1 : 0;
        m_axis_audio_out.write(s);
    }
}
